baseURL = "https://www.nerdalldebug.com"
languageCode = "pt-br"
title = "Nerd All Debug"
theme = "hugo-initio"
publishDir = "docs"

#Define the number of posts per page
paginate = 10

[params]
    name = "Nerd - Vanessa Valle"
    description = "Muito código entre conversas nerds!"
    email = "nerdalldebug@gmail.com"
    phone = "+234 23 9873237"
    address = "Rio de Janeiro - Brasil"
    year = 2018
    avatar = "images/nerdlogonomepeq.jpg"
    background = ""
    favicon = "images/favicon.ico"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[menu]
    [[menu.main]]
    name = "home"
    URL = "/"
    weight = 2

    [[menu.main]]
    name = "Blog"
    URL = "/posts/"
    weight = 3

    [[menu.main]]
    name = "Sobre"
    URL = "about"
    weight = 4

    



[params.disqus]
    site = "nerdalldebug.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nerdalldebug"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/vanessabrava"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/vanessabrava"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nerdalldebug"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/vanessa-valle-b1931a17/"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nerdalldebug.tumblr.com"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/vanessabrava"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:nerdalldebug@gmail.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"